### ISSUE TITLE
Please add OSS attribution for IntelliJ Community project

### ISSUE THREAD

**Issue by bulenkov** [krasa/IdeaIconPack#2]
The plugin contains icons from https://github.com/JetBrains/intellij-community but misses any links to IJ project. Could you please follow this guideline https://www.nexb.com/blog/oss_attribution_obligations.html to add OSS attribution?

**Comment by krasa** [comment]
Done.  https://github.com/krasa/IdeaIconPack/blob/master/NOTICE.txt

BTW, Any plans on bundling these old icons and making it user-friendly to choose between them?
