### ISSUE TITLE
Multiple plugins?

### ISSUE THREAD

**Issue by mallowigi** [krasa/IdeaIconPack#4]
Hi, I wonder if you can make multiple plugins of this one? For instance I see that you include 2016.1, 2017.1 and 2018.1 icons in the same plugin, making the plugin weigh 140 MB

Maybe you should separate it into multiple plugins ?

**Comment by krasa** [comment]
Well I could, but the compiled version is 3MB, the rest is only for generating schemes, so I don't see the point.

**Comment by mallowigi** [comment]
I see ok
