### ISSUE TITLE
Too many messages in IDEA system log

### ISSUE THREAD

**Issue by tanmatra** [krasa/IdeaIconPack#6]
With this plugin IDEA writes too many messages like this:

```2018-09-13 15:54:29,773 [18411011]   INFO - tellij.openapi.util.IconLoader - replace '/com/intellij/ide/ui/laf/icons/darcula/checkBoxSelected.png' with '/iconpack_2018_1/com/intellij/ide/ui/laf/icons/darcula/checkBoxSelected.png'```

There are hundreds or even thousands such lines in single log file. It pollutes log and can cause some slowdown. 

Could it not be so noisy?

**Comment by krasa** [comment]
Yes. JetBrains issue, nothing I can do.

**Comment by tanmatra** [comment]
Maybe it worth to open issue in IDEA tracker?

**Comment by krasa** [comment]
I measured that the logging on the start takes ~10ms total, every line takes 20-70us. Generally, they should be loaded only once, so I think that's fine.

**Comment by krasa** [comment]
You can update to the new version, I hope it's fine like that.
